apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: acm-operators
  namespace: openshift-gitops
spec:
  generators:
    - git:
        repoURL: https://github.com/luisevm/acm-policies-01.git
        revision: main
        directories:
          - path: operators/*
  template:
    metadata:
      name: 'acm-operators-{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/luisevm/acm-policies-01.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: acm-policies
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
